# Generated by Django 4.2.3 on 2023-08-19 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_lesson4", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="lesson4",
            table="advertisements",
        ),
    ]
